import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NavigationBar from './NavBar';
import Footer from './footer';
import { Container, ThemeProvider } from '@mui/material';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'FullCount Coffee',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<head>
				<link rel='icon' href='/favicon.ico' sizes='any' />
				<link rel='apple-touch-icon' href='/apple-icon?<generated>' type='image/<generated>' sizes='<generated>' />
			</head>
			<body className={inter.className}>
				<ThemeProvider theme={{}}>
					<NavigationBar />
					<Container fixed sx={{ py: '1em' }}>
						{children}
					</Container>
					<Footer />
				</ThemeProvider>
			</body>
		</html>
	);
}
